runtime: nodejs20

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

entrypoint: npm start

# Cloud SQL instance connection (Unix socket)
beta_settings:
  cloud_sql_instances: enhanced-oasis-481009-n3:us-central1:new-instance1

# Database connection environment variables
# DB_PASSWORD is fetched at runtime from Secret Manager (see secrets.js)
env_variables:
  DB_HOST: "/cloudsql/enhanced-oasis-481009-n3:us-central1:new-instance1"
  DB_USER: "dbuser"
  DB_NAME: "clientdb"
  DB_PASSWORD_SECRET: "db-password"  # Secret name in Secret Manager
  # DB_PORT and DB_SSL not needed for Unix socket connections
