steps:
  # Step 1: Install dependencies
  - name: node:20
    entrypoint: npm
    args: ["ci"]
    id: install

  # Step 2: Lint code (placeholder for code quality checks)
  - name: node:20
    entrypoint: npm
    args: ["run", "lint"]
    id: lint
    waitFor: ["install"]

  # Step 3: Run database migrations
  # Note: Migrations run during build with Cloud SQL connection
  - name: node:20
    entrypoint: npm
    args: ["run", "migrate"]
    id: migrate
    waitFor: ["lint"]
    env:
      - 'DB_HOST=/cloudsql/enhanced-oasis-481009-n3:us-central1:new-instance1'
      - 'DB_USER=dbuser'
      - 'DB_NAME=clientdb'
      - 'DB_PASSWORD_SECRET=db-password'
      - 'GOOGLE_CLOUD_PROJECT=enhanced-oasis-481009-n3'

  # Step 4: Deploy to App Engine
  - name: gcr.io/cloud-builders/gcloud
    args: ["app", "deploy", "app.yaml", "--quiet"]
    id: deploy
    waitFor: ["migrate"]

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY

# Service account permissions required:
# - roles/secretmanager.secretAccessor (for accessing db-password secret)
# - roles/appengine.appAdmin (for deploying to App Engine)
# - roles/cloudsql.client (for Cloud SQL connection during migrations)

# Note: Connection tests (npm test) are run locally before commit.
# Cloud Build focuses on: lint → migrate → deploy
